apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
 name: vm-network-bridges
spec:
 desiredState:
   interfaces:
     - type: linux-bridge
       name: br1
       state: up
       ipv4:
          enabled: false 
       description: Linux bridge with enp5s0f0 as a port
       bridge:
         options:
           stp:
             enabled: false
         port:
           - name: "enp5s0f0"

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-25
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 25}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-19
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 19}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-22
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 22}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-23
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 23}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-24
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 24}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-1
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 1}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-3
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 3}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-6
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 6}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-99
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 99}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-100
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 100}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network-4
  namespace: vm-import
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
spec:
  config: >- 
    {"name":"br1","type":"cnv-bridge","cniVersion":"0.3.1","bridge":"br1","macspoofchk": true,"vlan": 4}
